export const ADD_PRODUCTS = 'ADD_PRODUCTS';
export const CHANGE_PRODUCT = 'CHANGE_PRODUCT';
export const SAVE_CHANGES_PRODUCT = 'SAVE_CHANGES_PRODUCT';
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const CHANGE_OLD_FIELD = 'CHANGE_OLD_FIELD';
